/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.newpi.trabajofinal;

import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.text.View;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultKeyedValuesDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.ChartUtils;

/**
 *
 * @author Proyecto
 */


public class Frame1 extends javax.swing.JFrame {

    TablePaciente tbp = new TablePaciente();
    TableEnfermera tbe = new TableEnfermera();
    ImageIcon addIcon;
    ImageIcon editIcon;
    ImageIcon refreshIcon;
    ImageIcon deleteIcon;
    ImageIcon findIcon;
    ImageIcon favIcon;
    boolean modificado;
    String oldnum,oldnumEnfer;
    public static int IMAGE_WIDTH = 640;
    public static int IMAGE_HEIGHT = 480;
    
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        addIcon = new ImageIcon("");
        editIcon = new ImageIcon("/img/edit.png");
        refreshIcon = new ImageIcon("/img/refresh.png");
        deleteIcon = new ImageIcon("/img/delete.png");
        findIcon = new ImageIcon("/img/find.png");
        favIcon = new ImageIcon("/img/favicon.ico");
        initComponents();
        this.setIconImage(favIcon.getImage());
        tbPatients.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbPatients.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
              if( tbPatients.getSelectedRow()==-1)
                {
                btnModificarPaciente.setEnabled(false);
                btnEliminarPaciente.setEnabled(false);
                }
                else{
                btnModificarPaciente.setEnabled(true);
                btnEliminarPaciente.setEnabled(true);                
              }
            }
        });
        tbNurses.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tbNurses.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if(tbNurses.getSelectedRow()==-1)
                {
                btnModificarAdmin.setEnabled(false);
                btnEliminarEnfermera.setEnabled(false);
                }
                else 
                {
                  btnModificarAdmin.setEnabled(true);
                  btnEliminarEnfermera.setEnabled(true);
                }
            }
        });
        int patientCount = 0, doctorCount = 0;
        double salaireSum = 0;
        try {
            Conexion conn = new Conexion();
            patientCount = conn.patientCount();
            doctorCount = conn.doctorCount();
            salaireSum = conn.nurseSalaireSum();
        } catch(ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
        lblPatientCount.setText(Integer.toString(patientCount));
        lblDoctorCount.setText(Integer.toString(doctorCount));
        lblNurseSalaireSum.setText(Double.toString(salaireSum));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
            
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogAgregarPaciente = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtPatientNumber = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        txtPatientSurname = new javax.swing.JTextField();
        txtPatientAddress = new javax.swing.JTextField();
        txtPatientRoom = new javax.swing.JTextField();
        txtPatientPhone = new javax.swing.JTextField();
        txtPatientMut = new javax.swing.JTextField();
        txtPatientCodeService = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtPatientBed = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        dialogAgregarEnfermera = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtEnferNum = new javax.swing.JTextField();
        txtEnferNom = new javax.swing.JTextField();
        txtEnferApell = new javax.swing.JTextField();
        txtEnferCodServ = new javax.swing.JTextField();
        txtEnferRotacion = new javax.swing.JTextField();
        txtEnferSalario = new javax.swing.JTextField();
        txtEnferTelefono = new javax.swing.JTextField();
        txtEnferDireccion = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btnSave1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        lblPatientCount = new javax.swing.JLabel();
        btnPatientReport = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        lblDoctorCount = new javax.swing.JLabel();
        btnDoctorReport = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        lblNurseSalaireSum = new javax.swing.JLabel();
        btnNurseReport1 = new javax.swing.JButton();
        btnNurseReport2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificarPaciente = new javax.swing.JButton();
        btnAgPaciente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPatients = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        txtService = new javax.swing.JTextField();
        btnEliminarPaciente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnExportPatientsToCSV = new javax.swing.JButton();
        btnExportPatientsToExcel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCodEnfer = new javax.swing.JTextField();
        txtCodNom = new javax.swing.JTextField();
        txtCodApell = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEliminarEnfermera = new javax.swing.JButton();
        btnAgregarAdmin = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbNurses = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnModificarAdmin = new javax.swing.JButton();
        btnExportNursesToCSV = new javax.swing.JButton();
        btnExportNursesToExcel = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();

        dialogAgregarPaciente.setTitle("Paciente");
        dialogAgregarPaciente.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogAgregarPaciente.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                dialogAgregarPacienteWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dialogAgregarPacienteWindowOpened(evt);
            }
        });

        jLabel7.setText("Número:");

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        txtPatientRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientRoomActionPerformed(evt);
            }
        });

        jLabel8.setText("Nombre:");

        jLabel10.setText("Apellido:");

        jLabel11.setText("Dirección:");

        jLabel12.setText("Teléfono:");

        jLabel13.setText("Mutuo:");

        jLabel14.setText("Código de Servicio:");

        jLabel15.setText("Número de Habitación:");

        btnSave.setText("Guardar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel16.setText("Número de cama:");

        txtPatientBed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientBedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientNumber))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtPatientSurname))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPatientAddress))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(23, 23, 23)
                        .addComponent(txtPatientMut))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(11, 11, 11)
                        .addComponent(txtPatientPhone))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientCodeService))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientBed))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPatientRoom))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtPatientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtPatientSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtPatientAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPatientPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtPatientMut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPatientCodeService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtPatientRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientBed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout dialogAgregarPacienteLayout = new javax.swing.GroupLayout(dialogAgregarPaciente.getContentPane());
        dialogAgregarPaciente.getContentPane().setLayout(dialogAgregarPacienteLayout);
        dialogAgregarPacienteLayout.setHorizontalGroup(
            dialogAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAgregarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogAgregarPacienteLayout.setVerticalGroup(
            dialogAgregarPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAgregarPacienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dialogAgregarPaciente.getAccessibleContext().setAccessibleParent(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        dialogAgregarEnfermera.setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        dialogAgregarEnfermera.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                dialogAgregarEnfermeraWindowOpened(evt);
            }
        });

        jLabel18.setText("Número:");

        txtEnferNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnferNomActionPerformed(evt);
            }
        });

        txtEnferApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnferApellActionPerformed(evt);
            }
        });

        txtEnferTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnferTelefonoActionPerformed(evt);
            }
        });

        txtEnferDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnferDireccionActionPerformed(evt);
            }
        });

        jLabel19.setText("Nombre:");

        jLabel20.setText("Apellido:");

        jLabel21.setText("Codigo Servicio:");

        jLabel22.setText("Rotacion:");

        jLabel23.setText("Salario");

        jLabel24.setText("Telefono:");

        jLabel25.setText("Dirección:");

        btnSave1.setText("Guardar");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });

        btnCancel1.setText("Cancelar");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnferNum))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnferNom))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(txtEnferApell))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEnferCodServ))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(23, 23, 23)
                        .addComponent(txtEnferSalario))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(11, 11, 11)
                        .addComponent(txtEnferRotacion))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnferTelefono))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEnferDireccion))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(31, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtEnferNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(txtEnferNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(txtEnferApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtEnferCodServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtEnferRotacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtEnferSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtEnferTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtEnferDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dialogAgregarEnfermeraLayout = new javax.swing.GroupLayout(dialogAgregarEnfermera.getContentPane());
        dialogAgregarEnfermera.getContentPane().setLayout(dialogAgregarEnfermeraLayout);
        dialogAgregarEnfermeraLayout.setHorizontalGroup(
            dialogAgregarEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAgregarEnfermeraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogAgregarEnfermeraLayout.setVerticalGroup(
            dialogAgregarEnfermeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogAgregarEnfermeraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        dialogAgregarEnfermera.getAccessibleContext().setAccessibleParent(null);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA ADMINISTRATIVO - HOSPITAL");

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("Número de Pacientes");

        lblPatientCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblPatientCount.setText("0");

        btnPatientReport.setText("Pacientes por Servicio");
        btnPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnPatientReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPatientCount, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblPatientCount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnPatientReport, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel28.setText("Número de Doctores");

        lblDoctorCount.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblDoctorCount.setText("0");

        btnDoctorReport.setText("Doctores por Especialidad");
        btnDoctorReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDoctorCount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoctorReport, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblDoctorCount, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDoctorReport, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel29.setText("Salario Total de Enfermeras");

        lblNurseSalaireSum.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        lblNurseSalaireSum.setText("0");

        btnNurseReport1.setText("Enfermeras por Turno");
        btnNurseReport1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseReport1ActionPerformed(evt);
            }
        });

        btnNurseReport2.setText("Enfermeras por Servicio y Turno");
        btnNurseReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNurseReport2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(lblNurseSalaireSum, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnNurseReport1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNurseReport2)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblNurseSalaireSum, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNurseReport1, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(btnNurseReport2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Doctor", jPanel4);

        txtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberActionPerformed(evt);
            }
        });
        txtNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumberKeyReleased(evt);
            }
        });

        jLabel1.setText("Numero Paciente:");

        jLabel2.setText("Servicio Otorgado:");

        jLabel6.setText("Nombre Paciente:");

        btnModificarPaciente.setText("Modificar");
        btnModificarPaciente.setEnabled(false);
        btnModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPacienteActionPerformed(evt);
            }
        });

        btnAgPaciente.setIcon(addIcon);
        btnAgPaciente.setText("Agregar");
        btnAgPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgPacienteActionPerformed(evt);
            }
        });

        tbPatients.setModel(tbp);
        jScrollPane1.setViewportView(tbPatients);

        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txtNameMouseReleased(evt);
            }
        });
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        txtService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceActionPerformed(evt);
            }
        });
        txtService.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtServiceKeyReleased(evt);
            }
        });

        btnEliminarPaciente.setText("Eliminar");
        btnEliminarPaciente.setEnabled(false);
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });

        jLabel9.setText("Datos del paciente:");

        btnExportPatientsToCSV.setText("Exportar a CSV");
        btnExportPatientsToCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPatientsToCSVActionPerformed(evt);
            }
        });

        btnExportPatientsToExcel.setText("Exportar a Excel");
        btnExportPatientsToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportPatientsToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(txtNumber))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(45, 45, 45)
                        .addComponent(txtName))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnExportPatientsToExcel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnExportPatientsToCSV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminarPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgPaciente))
                            .addComponent(txtService))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnExportPatientsToCSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExportPatientsToExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Enfermera", jPanel2);

        jLabel3.setText("Codigo enfermera:");

        txtCodEnfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodEnferActionPerformed(evt);
            }
        });
        txtCodEnfer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodEnferKeyReleased(evt);
            }
        });

        txtCodNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodNomActionPerformed(evt);
            }
        });
        txtCodNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodNomKeyReleased(evt);
            }
        });

        txtCodApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodApellActionPerformed(evt);
            }
        });
        txtCodApell.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodApellKeyReleased(evt);
            }
        });

        jLabel4.setText("Datos de la enfermera:");

        btnEliminarEnfermera.setText("Eliminar");
        btnEliminarEnfermera.setEnabled(false);
        btnEliminarEnfermera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarEnfermeraActionPerformed(evt);
            }
        });

        btnAgregarAdmin.setText("Agregar");
        btnAgregarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdminActionPerformed(evt);
            }
        });

        tbNurses.setModel(tbe);
        jScrollPane3.setViewportView(tbNurses);

        jLabel5.setText("Nombre enfermera:");

        jLabel17.setText("Apellido enfermera:");

        btnModificarAdmin.setText("Modificar");
        btnModificarAdmin.setEnabled(false);
        btnModificarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAdminActionPerformed(evt);
            }
        });

        btnExportNursesToCSV.setText("Exportar a CSV");
        btnExportNursesToCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportNursesToCSVActionPerformed(evt);
            }
        });

        btnExportNursesToExcel.setText("Exportar a Excel");
        btnExportNursesToExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportNursesToExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodApell, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodEnfer)
                            .addComponent(txtCodNom)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExportNursesToExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExportNursesToCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnModificarAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarEnfermera)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgregarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodEnfer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodApell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEliminarEnfermera, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModificarAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportNursesToCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnExportNursesToExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Administrador", jPanel3);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("SISTEMA ADMINISTRATIVO - HOSPITAL");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jTabbedPane2.getAccessibleContext().setAccessibleName("Enfermera");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceActionPerformed

    private void txtNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumberKeyReleased
        tbp.filter(txtNumber.getText(), txtName.getText(), txtService.getText());
        tbPatients.repaint();
        tbPatients.clearSelection();
    }//GEN-LAST:event_txtNumberKeyReleased

    private void txtNameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameMouseReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        tbp.filter(txtNumber.getText(), txtName.getText(), txtService.getText());
        tbPatients.repaint();
        tbPatients.clearSelection();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtServiceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtServiceKeyReleased
        tbp.filter(txtNumber.getText(), txtName.getText(), txtService.getText());
        tbPatients.repaint();
        tbPatients.clearSelection();
    }//GEN-LAST:event_txtServiceKeyReleased

    private void btnModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPacienteActionPerformed
        dialogAgregarPaciente.setTitle("Modificar Paciente");
        Paciente p = tbp.getPatientAt(tbPatients.getSelectedRow());
        oldnum = p.getNumero();
        txtPatientNumber.setText(p.getNumero());
        txtPatientName.setText(p.getNombre());
        txtPatientSurname.setText(p.getApellido());
        txtPatientAddress.setVisible(false);
        txtPatientPhone.setVisible(false);
        txtPatientMut.setVisible(false);
        txtPatientCodeService.setText(p.getCodeService());
        txtPatientRoom.setText(p.getRoomNumber());
        txtPatientBed.setText(p.getLit());
        modificado=true;
        dialogAgregarPaciente.setVisible(true);
    }//GEN-LAST:event_btnModificarPacienteActionPerformed

    private void btnAgPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgPacienteActionPerformed
        Limpiar();        
        dialogAgregarPaciente.setTitle("Agregar Paciente");
        modificado=false;
        dialogAgregarPaciente.setVisible(true);
    }//GEN-LAST:event_btnAgPacienteActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar el paciente?");
       if(dialogResult == JOptionPane.YES_OPTION) {
           try {
               new Conexion().deletePatient(tbp.getNumeroAt(tbPatients.getSelectedRow()));
               JOptionPane.showMessageDialog(this, "Se eliminó el paciente con éxito");
               tbp.filter(txtNumber.getText(), txtName.getText(), txtService.getText());
                tbPatients.repaint();
           } catch (ClassNotFoundException | SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getStackTrace(), "Ocurrió un problema", JOptionPane.ERROR_MESSAGE);
           }
       }
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void txtPatientRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientRoomActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
     dialogAgregarPaciente.setVisible(false);     
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String  num= txtPatientNumber.getText();
        String nom=txtPatientName.getText();
        String surna=txtPatientSurname.getText();
        String dir = txtPatientAddress.getText();
        String codser= txtPatientCodeService.getText();
        String telf= txtPatientNumber.getText();
        String room=txtPatientRoom.getText();
        String Mut=txtPatientMut.getText();
        String cama=txtPatientBed.getText();
        String cmd,cmd2,mensaje;
        
        if(!modificado){
                cmd=String.format(
                "insert into malade(numero,nom,prenom,adresse,tel,mutuelle) "
                +"values('%s','%s','%s','%s','%s','%s');"
                ,num,nom,surna,dir,codser,telf,room,Mut);
                mensaje="Paciente Agregado con exito";
               cmd2=String.format(
                "insert into hospitalisation(no_malade,code_service,no_chambre,lit) values ("
                +"'%s','%s','%s','%s' )"
                ,num,codser,room,cama);
                mensaje="Paciente Agregado con exito";        
                
        }
        else
        {
           cmd=String.format(
                "update malade set"
                +" numero='%s',nom='%s',prenom='%s' "+
                "where "+
                "numero='%s' "
                ,num,nom,surna,oldnum);
           
           cmd2=String.format(
                "update hospitalisation set "
                +"no_malade=%s,code_service='%s',no_chambre='%s',lit='%s' where "
                        + "no_malade=%s"
                ,num,codser,room,cama,oldnum);
           mensaje="Datos del paciente modificados correctamente";
        }
        try {
            new Conexion().exec(cmd);
            new Conexion().exec(cmd2);
          JOptionPane.showMessageDialog(this, mensaje);
        tbp.filter(txtNumber.getText(), txtName.getText(), txtService.getText());
        tbPatients.repaint();
        tbPatients.clearSelection();
        dialogAgregarPaciente.setVisible(false);
        } catch (ClassNotFoundException|SQLException ex) {
               JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un problema", JOptionPane.ERROR_MESSAGE);
               ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed
private void Limpiar()
{
        txtPatientAddress.setText("");
        txtPatientBed.setText("");
        txtPatientCodeService.setText("");
        txtPatientMut.setText("");
        txtPatientName.setText("");
        txtPatientNumber.setText("");
        txtPatientPhone.setText("");
        txtPatientRoom.setText("");
        txtPatientSurname.setText("");     
        
}
private void LimpiarEnfer()
{
    txtEnferApell.setText("");
    txtEnferCodServ.setText("");
    txtEnferDireccion.setText("");
    txtEnferNom.setText("");
    txtEnferNum.setText("");
    txtEnferRotacion.setText("");
    txtEnferSalario.setText("");
    txtEnferTelefono.setText("");
}
    private void dialogAgregarPacienteWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogAgregarPacienteWindowClosed
  
    }//GEN-LAST:event_dialogAgregarPacienteWindowClosed

    private void dialogAgregarPacienteWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogAgregarPacienteWindowOpened
        dialogAgregarPaciente.pack();
    }//GEN-LAST:event_dialogAgregarPacienteWindowOpened

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void txtPatientBedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientBedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientBedActionPerformed

    private void txtEnferNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnferNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnferNomActionPerformed

    private void txtEnferDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnferDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnferDireccionActionPerformed

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave1ActionPerformed
        String  num= txtEnferNum.getText();
        String nom=txtEnferNom.getText();
        String surna=txtEnferApell.getText();
        String dir = txtEnferDireccion.getText();
        String codser= txtEnferCodServ.getText();
        String telf= txtEnferTelefono.getText();
        String salario=txtEnferSalario.getText();
        String rotacion=txtEnferRotacion.getText();
        String cmd,cmd2,mensaje;
        if(!modificado)
        {
            cmd=String.format("insert into employe(numero,nom,prenom,adresse,tel) values('%s','%s','%s','%s','%s'); "
                    ,num,nom,surna,dir,telf);
            cmd2=String.format("insert into infirmier(numero,code_service,rotation,salaire) "
                    + "values ('%s','%s','%s','%s')",num,codser,rotacion,salario);
            mensaje="Datos del paciente agregados correctamente";
        }
        else
        {
            cmd=String.format(
                "update employe set"
                +" numero='%s',nom='%s',prenom='%s', adresse= '%s', tel='%s' "+
                "where numero='%s' "
                ,num,nom,surna,dir,telf,oldnumEnfer);
           cmd2=String.format(
                "update infirmier set "
                +"numero=%s,code_service='%s',rotation='%s',salaire='%s' where "
                        + "numero=%s"
                ,num,codser,rotacion,salario,oldnumEnfer);
           mensaje="Datos del paciente modificados correctamente";
        }
        try {
            new Conexion().exec(cmd);
            new Conexion().exec(cmd2);
            JOptionPane.showMessageDialog(this, mensaje);     
        tbe.filter(txtCodEnfer.getText(), txtCodNom.getText(),txtCodApell.getText());
        tbNurses.repaint();
        tbNurses.clearSelection();
        dialogAgregarEnfermera.setVisible(false);
        } catch (ClassNotFoundException |SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un problema", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        } 
        
    }//GEN-LAST:event_btnSave1ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        dialogAgregarEnfermera.setVisible(false);
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void txtEnferTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnferTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnferTelefonoActionPerformed

    private void txtEnferApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnferApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnferApellActionPerformed

    private void dialogAgregarEnfermeraWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_dialogAgregarEnfermeraWindowOpened
      dialogAgregarEnfermera.pack();
      LimpiarEnfer();
    }//GEN-LAST:event_dialogAgregarEnfermeraWindowOpened

    private void btnModificarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAdminActionPerformed
        dialogAgregarEnfermera.setTitle("Modificar Enfermera");
        Enfermera E= tbe.getEnfermeraAt(tbNurses.getSelectedRow());
        oldnumEnfer = E.getNumero();
        txtEnferNum.setText(E.getNumero());
        txtEnferNom.setText(E.getNombre());
        txtEnferApell.setText(E.getApellido());
        txtEnferCodServ.setText(E.getCodServicio());
        txtEnferDireccion.setText(E.getDireccion());
        txtEnferRotacion.setText(E.getRotacion());
        txtEnferSalario.setText(E.getSalario());
        txtEnferTelefono.setText(E.getNumero());
        modificado=true;
        dialogAgregarEnfermera.setVisible(true);
        dialogAgregarEnfermera.pack();
    }//GEN-LAST:event_btnModificarAdminActionPerformed

    private void btnAgregarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAdminActionPerformed
        LimpiarEnfer();
        dialogAgregarEnfermera.setTitle("Agregar Enfermera");
        dialogAgregarEnfermera.setVisible(true);
        dialogAgregarEnfermera.pack();
        modificado=false;
    }//GEN-LAST:event_btnAgregarAdminActionPerformed

    private void btnEliminarEnfermeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarEnfermeraActionPerformed
        int dialogResult= JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar a la enfermera?");
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            try {
                new Conexion().deleteNurse(tbe.getNumeroAt(tbNurses.getSelectedRow()));
                JOptionPane.showMessageDialog(this, "Se eliminó a la enfermera con éxito");
                tbe.filter(txtCodEnfer.getText(), txtCodNom.getText(), txtCodApell.getText());
                tbNurses.repaint();
                tbNurses.clearSelection();
            } catch (ClassNotFoundException |SQLException ex ) {
                JOptionPane.showMessageDialog(this, ex.getStackTrace(), "Ocurrió un problema", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnEliminarEnfermeraActionPerformed

    private void txtCodApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodApellActionPerformed

    private void txtCodNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodNomActionPerformed

    private void txtCodEnferKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodEnferKeyReleased
        tbe.filter(txtCodEnfer.getText(), txtCodNom.getText(), txtCodApell.getText());
        tbNurses.repaint();
        tbNurses.clearSelection();
    }//GEN-LAST:event_txtCodEnferKeyReleased

    private void txtCodEnferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodEnferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodEnferActionPerformed

    private void txtCodNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodNomKeyReleased
        tbe.filter(txtCodEnfer.getText(), txtCodNom.getText(), txtCodApell.getText());
        tbNurses.repaint();
        tbNurses.clearSelection();
    }//GEN-LAST:event_txtCodNomKeyReleased

    private void txtCodApellKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodApellKeyReleased
        tbe.filter(txtCodEnfer.getText(), txtCodNom.getText(), txtCodApell.getText());
        tbNurses.repaint();
        tbNurses.clearSelection();
    }//GEN-LAST:event_txtCodApellKeyReleased

    private void btnPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientReportActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            List<Object[]> result = new Conexion().patientReport1();
            result.stream().forEach(o -> { dataset.setValue((int)o[0], "# Pacientes", (String)o[1]); });
        }
        catch(ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
        JFreeChart chart = ChartFactory.createBarChart("Pacientes por Servicio Ofrecido", "Servicios", "# Pacientes", dataset, PlotOrientation.VERTICAL, false, true, false);      
        JFrame frame = new JFrame("Pacientes por Servicio ofrecido");
        frame.setLayout(new BorderLayout());
        frame.add("North", new ChartPanel(chart));
        JButton btn = new JButton("Guardar como Imagen");
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    File file = new File("reports/Reporte de Pacientes por Servicio Ofrecido.png");
                    ChartUtils.saveChartAsPNG(file, chart, IMAGE_WIDTH, IMAGE_HEIGHT);
                    JOptionPane.showMessageDialog(frame, "Se guardó la imagen en: " + file.getAbsolutePath());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(frame, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        frame.add("South", btn);
        frame.setVisible(true);
        frame.pack();
    }//GEN-LAST:event_btnPatientReportActionPerformed

    private void btnDoctorReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorReportActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            List<Object[]> result = new Conexion().doctorReport1();
            result.stream().forEach(o -> { dataset.setValue((int)o[0], "# Doctores", (String)o[1]); });
        }
        catch(ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
        JFreeChart chart = ChartFactory.createBarChart("Doctores por Especialidad", "Especialidad", "# Doctores", dataset, PlotOrientation.HORIZONTAL, false, true, false);
        JFrame frame = new JFrame("Doctores por Especialidad");
        frame.setLayout(new BorderLayout());
        frame.add("North", new ChartPanel(chart));
        JButton btn = new JButton("Guardar como Imagen");
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    File file = new File("reports/Reporte de Doctores por Especialidad.png");
                    ChartUtils.saveChartAsPNG(file, chart, IMAGE_WIDTH, IMAGE_HEIGHT);
                    JOptionPane.showMessageDialog(frame, "Se guardó la imagen en: " + file.getAbsolutePath());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(frame, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        frame.add("South", btn);
        frame.setVisible(true);
        frame.pack();
    }//GEN-LAST:event_btnDoctorReportActionPerformed

    private void btnNurseReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseReport2ActionPerformed
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            List<Object[]> result = new Conexion().nurseReport2();
            result.stream().forEach(o -> { dataset.setValue((int)o[0], (String)o[2], (String)o[1]); });
        }
        catch(ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
        JFreeChart chart = ChartFactory.createBarChart("Enfermeras por Especialidad y Turno", "Especialidad", "# Enfermeras", dataset, PlotOrientation.VERTICAL, true, true, false);
        JFrame frame = new JFrame("Enfermeras por Turno y Servicio");
        frame.setLayout(new BorderLayout());
        frame.add("North", new ChartPanel(chart));
        JButton btn = new JButton("Guardar como Imagen");
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    File file = new File("reports/Reporte de Enfermeras por Turno y Servicio.png");
                    ChartUtils.saveChartAsPNG(file, chart, IMAGE_WIDTH, IMAGE_HEIGHT);
                    JOptionPane.showMessageDialog(frame, "Se guardó la imagen en: " + file.getAbsolutePath());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(frame, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        frame.add("South", btn);
        frame.setVisible(true);
        frame.pack();
    }//GEN-LAST:event_btnNurseReport2ActionPerformed

    private void btnNurseReport1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNurseReport1ActionPerformed
        DefaultPieDataset dataset = new DefaultPieDataset();
        try {
            List<Object[]> result = new Conexion().nurseReport1();
            result.stream().forEach(o -> { dataset.setValue((String)o[1], (int)o[0]); });
        }
        catch(ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
        JFreeChart chart = ChartFactory.createPieChart("Enfermeras por turno", dataset);
        JFrame frame = new JFrame("Enfermeras por Turno");
        frame.setLayout(new BorderLayout());
        frame.add("North", new ChartPanel(chart));
        JButton btn = new JButton("Guardar como Imagen");
        btn.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    File file = new File("reports/Reporte de Enfermeras por Turno.png");
                    ChartUtils.saveChartAsPNG(file, chart, IMAGE_WIDTH, IMAGE_HEIGHT);
                    JOptionPane.showMessageDialog(frame, "Se guardó la imagen en: " + file.getAbsolutePath());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(frame, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
        frame.add("South", btn);

        frame.setVisible(true);
        frame.pack();
    }//GEN-LAST:event_btnNurseReport1ActionPerformed

    private void btnExportNursesToCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportNursesToCSVActionPerformed
        try {
            File file = new File("reports/enfermeras.csv");
            ExportHelper.jTableToCSV(tbNurses, file);
            JOptionPane.showMessageDialog(this, "Se guardó el archivo en: " + file.getAbsolutePath());
        }
        catch(IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportNursesToCSVActionPerformed

    private void btnExportNursesToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportNursesToExcelActionPerformed
        try {
            File file = new File("reports/enfermeras.xls");
            ExportHelper.jTableToExcel(tbNurses, file);
            JOptionPane.showMessageDialog(this, "Se guardó el archivo en: " + file.getAbsolutePath());
        }
        catch(IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportNursesToExcelActionPerformed

    private void btnExportPatientsToExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPatientsToExcelActionPerformed
        try {
            File file = new File("reports/pacientes.xls");
            ExportHelper.jTableToExcel(tbPatients, file);
            JOptionPane.showMessageDialog(this, "Se guardó el archivo en: " + file.getAbsolutePath());
        }
        catch(IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportPatientsToExcelActionPerformed

    private void btnExportPatientsToCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportPatientsToCSVActionPerformed
        try {
            File file = new File("reports/pacientes.csv");
            ExportHelper.jTableToCSV(tbPatients, file);
            JOptionPane.showMessageDialog(this, "Se guardó el archivo en: " + file.getAbsolutePath());
        }
        catch(IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Ocurrió un error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExportPatientsToCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgPaciente;
    private javax.swing.JButton btnAgregarAdmin;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnDoctorReport;
    private javax.swing.JButton btnEliminarEnfermera;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnExportNursesToCSV;
    private javax.swing.JButton btnExportNursesToExcel;
    private javax.swing.JButton btnExportPatientsToCSV;
    private javax.swing.JButton btnExportPatientsToExcel;
    private javax.swing.JButton btnModificarAdmin;
    private javax.swing.JButton btnModificarPaciente;
    private javax.swing.JButton btnNurseReport1;
    private javax.swing.JButton btnNurseReport2;
    private javax.swing.JButton btnPatientReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSave1;
    private javax.swing.JDialog dialogAgregarEnfermera;
    private javax.swing.JDialog dialogAgregarPaciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblDoctorCount;
    private javax.swing.JLabel lblNurseSalaireSum;
    private javax.swing.JLabel lblPatientCount;
    private javax.swing.JTable tbNurses;
    private javax.swing.JTable tbPatients;
    private javax.swing.JTextField txtCodApell;
    private javax.swing.JTextField txtCodEnfer;
    private javax.swing.JTextField txtCodNom;
    private javax.swing.JTextField txtEnferApell;
    private javax.swing.JTextField txtEnferCodServ;
    private javax.swing.JTextField txtEnferDireccion;
    private javax.swing.JTextField txtEnferNom;
    private javax.swing.JTextField txtEnferNum;
    private javax.swing.JTextField txtEnferRotacion;
    private javax.swing.JTextField txtEnferSalario;
    private javax.swing.JTextField txtEnferTelefono;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNumber;
    private javax.swing.JTextField txtPatientAddress;
    private javax.swing.JTextField txtPatientBed;
    private javax.swing.JTextField txtPatientCodeService;
    private javax.swing.JTextField txtPatientMut;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPatientNumber;
    private javax.swing.JTextField txtPatientPhone;
    private javax.swing.JTextField txtPatientRoom;
    private javax.swing.JTextField txtPatientSurname;
    private javax.swing.JTextField txtService;
    // End of variables declaration//GEN-END:variables
}
